version: "3"
services:
  shape-shifter:
    image: shape-shifter
    build: .
    ports:
      - "3000:3000"
    command: sh -c "yarn && yarn dev"
    environment:
      APP_PORT: "3000"
    volumes:
      - .:/app
